version: '2'


services:

  master-nodeexporter:
    extends:
      file: docker-compose.yml
      service: master-nodeexporter

  master-cadvisor:
    extends:
      file: docker-compose.yml
      service: master-cadvisor
    ports:
      - 8080:8080

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
    ports:
      - 9090:9090

  blackboxprober:
    extends:
      file: docker-compose.yml
      service: blackboxprober
    ports:
      - 9115:9115

  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  alertmanager:
    extends:
      file: docker-compose.yml
      service: alertmanager
    ports:
      - 9093:9093

networks:
  default:
    external:
      name: monitoring_logging
